Add Brazilian Portuguese translation
rugk/awesome-emoji-picker pull request #108
Opened 2020-10-30 21:05 UTC by marceloaof

Hello❗(emoji extracted from Awesome Emoji Picker)

I am creating the translation for Brazilian Portuguese as a pull request, according to what was required on https://github.com/rugk/awesome-emoji-picker/issues/107

This is my first pull request on GitHub, so please inform me if any errors were made.

@rugk, I translated the add-on listings on AMO as well, after you mentioned it.

2020-11-02 18:44 UTC, rugk commented
Hi @marceloaof,
thanks for your first contribution to this project! :tada: :+1: 🏅
I hope you'll like this project and enjoy hacking on it… :smiley:

Thanks for your translation.
Please subscribe to #27 to get notified for new updates on translations etc. :smiley:

I'll review this soon.

2020-11-02 18:47 UTC, rugk requested changes
Only one small change. Otherwise LGTM.

So congratulations to your first PR! :smiley:

2020-11-02 18:47 UTC, rugk commented on src/_locales/pt-BR/messages.json
> +    "message": "rugk",
I guess you should add yourself here (and link to you above). See https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#translator-credit-inside-of-add-on

2020-11-02 21:08 UTC, marceloaof commented
Vielen Dank for your guidance, @rugk 😘 Now I understand my errors on GitHub thanks to you.

Following your suggestion, I have subscribed myself to receive notifications about new translations. Therefore, I will be able to assist in translating the project when it is available to translate the names of the emojis. 📝 Recently, [other project](https://github.com/vector-im/element-web/issues/11013) was able to achieve that. I inform you in the hope to advance that scenario here.

Rugk, what on German do you mean by hacking on it? 🙃 Hab viel Spass?

2020-11-03 09:01 UTC, rugk commented
Well hacking on it is just what you do, contributing to it. Was just little colloquial term [referring to the original meaning](https://de.wikipedia.org/wiki/Hacker).

2020-11-03 09:01 UTC, rugk approved these changes

2020-11-03 09:10 UTC, rugk commented
Ah BTW another question: Could we use it for `pt` (i.e. portguese, all variants) or does it need to be only shown for `pt-BR`?

2020-11-03 09:11 UTC, rugk approved these changes
Requesting a potential review from @CGReinhold (Portuguese translator in Offline QR Code). Unless there are objections, this will be merged soon.

2020-11-03 09:29 UTC, CGReinhold approved these changes

2020-11-03 22:11 UTC, marceloaof commented
Hello, @rugk
👍 Undoubtedly, reading Brazilian Portuguese on this add-on is a better experience for natives of Portugal, Angola and other countries than English currently is.
👉 However, while people say in Portuguese from Portugal (and in German) that "du kannst und das Add-on kann", in Brazilian Portuguese people say "du kann und und Add-on kann".
🔜 The translation I sent is understandable to Portuguese readers, but some nuances will be noticeable to non-Brazilians.
You may either offer the translation as portuguese in general (pt), making the distinction in the future, or offer it duplicated (pt-br + pt). A native from Portugal will need to make low priority corrections for the translation granted to Portugal.

2020-11-04 10:23 UTC, rugk commented
Well, what is/are your suggestions, @marceloaof and @CGReinhold? As I don't know this language I don't know how big the distraction would be to offer it as `pt`.

2020-11-04 19:59 UTC, CGReinhold commented
I don't think that it would be a big problem offering it as `pt` since the differences are not big and most softwares already have only the brazilian portuguese option. Since there isn't currently a Portuguese translator, I believe that this is the way to go.

2020-11-05 23:04 UTC, CGReinhold approved these changes

2020-11-08 15:21 UTC, merged